name: Python application

on: [pull_request]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt
          pip install pipenv codecov

      - name: Lint with flake8.
        run: |
          python -m flake8 .

      - name: Automatic GA tests.
        run: |
          pytest libpythonprojat2022 --cov=libpythonprojat2022
          
